'use client';

import React from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { FaCalculator, FaLeaf, FaCreditCard, FaChartPie, FaGlobeAmericas, FaUserFriends } from 'react-icons/fa';

// Animation variants
const fadeIn = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: {
      duration: 0.6,
      ease: [0.1, 0.9, 0.2, 1]
    }
  }
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.2,
      delayChildren: 0.1,
    }
  }
};

export default function ForIndividuals() {
  // Individual solutions data
  const solutions = [
    {
      icon: <FaCalculator className="w-8 h-8" />,
      title: "Carbon Footprint Calculator",
      description: "Understand your personal impact with our comprehensive calculator that analyzes your lifestyle choices, travel habits, home energy use, and diet."
    },
    {
      icon: <FaLeaf className="w-8 h-8" />,
      title: "Personal Offset Subscriptions",
      description: "Subscribe to monthly carbon offset plans tailored to your lifestyle, automatically offsetting your carbon footprint while you live your life."
    },
    {
      icon: <FaCreditCard className="w-8 h-8" />,
      title: "One-Time Offset Purchases",
      description: "Make one-time carbon offset purchases for specific activities like flights, road trips, or events to neutralize their environmental impact."
    },
    {
      icon: <FaChartPie className="w-8 h-8" />,
      title: "Personalized Action Plans",
      description: "Receive customized recommendations to reduce your emissions based on your unique lifestyle, with progress tracking and achievement badges."
    },
    {
      icon: <FaGlobeAmericas className="w-8 h-8" />,
      title: "Project Selection",
      description: "Choose which verified carbon projects you want to support, from reforestation to renewable energy, based on your personal values."
    },
    {
      icon: <FaUserFriends className="w-8 h-8" />,
      title: "Community Challenges",
      description: "Join community challenges to reduce your carbon footprint alongside others, sharing tips and celebrating collective impact."
    }
  ];

  // Impact data
  const impactNumbers = [
    { value: "20K+", label: "Individual Users" },
    { value: "500K+", label: "Tons Offset" },
    { value: "120+", label: "Projects Supported" },
    { value: "30+", label: "Countries" }
  ];

  // Common questions
  const faqs = [
    {
      question: "What is my carbon footprint?",
      answer: "Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by your actions. The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world."
    },
    {
      question: "How accurate is the carbon calculator?",
      answer: "Our calculator uses the latest emissions factors and scientific data to provide a good estimate of your carbon footprint. While no calculator can be 100% precise, ours considers detailed aspects of your lifestyle including travel, home energy, diet, and consumption patterns."
    },
    {
      question: "How do carbon offsets work?",
      answer: "Carbon offsets work by supporting projects that reduce greenhouse gas emissions elsewhere, effectively 'offsetting' your own emissions. When you purchase offsets, you're investing in projects like renewable energy, reforestation, or methane capture that remove or prevent emissions."
    },
    {
      question: "How do I know my offsets are making a difference?",
      answer: "All our offset projects are verified by independent third parties using internationally recognized standards (like Gold Standard or Verified Carbon Standard). We provide transparent reporting on project impacts and regularly share updates about the projects you support."
    },
    {
      question: "What's the difference between carbon reduction and carbon offsetting?",
      answer: "Reduction means lowering your actual emissions by changing behavior or using more efficient technologies. Offsetting compensates for emissions you cannot avoid by supporting projects that reduce emissions elsewhere. Both are important parts of climate action."
    }
  ];

  return (
    <main className="min-h-screen">
      {/* Hero Section */}
      <section className="page-header">
        <div className="page-header-content">
          <motion.div 
            className="max-w-3xl"
            initial="hidden"
            animate="visible"
            variants={fadeIn}
          >
            <h1 className="page-title">Take Climate Action Today</h1>
            <p className="page-description">
              Calculate, reduce, and offset your carbon footprint with our easy-to-use platform designed for individuals who want to make a positive environmental impact.
            </p>
            <motion.div 
              className="mt-8 flex flex-col sm:flex-row gap-4"
              variants={fadeIn}
            >
              <Link href="/calculator" className="btn btn-primary hover-lift">
                Calculate Your Footprint
              </Link>
              <Link href="#solutions" className="btn btn-outline hover-lift">
                Explore Solutions
              </Link>
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="section">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="text-center mb-16"
          >
            <h2 className="text-3xl font-bold text-dark-forest dark:text-pale-lime mb-5">How It Works</h2>
            <p className="max-w-3xl mx-auto text-gray-700 dark:text-gray-300">
              Taking climate action is simple with our three-step process designed to help you understand, reduce, and offset your carbon footprint.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-3 grid-gap-lg">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              variants={fadeIn}
              className="text-center"
            >
              <div className="relative mx-auto mb-6 w-20 h-20 flex items-center justify-center bg-sage/20 rounded-full shadow-inner">
                <span className="text-dark-forest font-bold text-3xl">1</span>
                <div className="absolute -right-10 top-5 hidden md:block w-24 h-1 bg-gradient-to-r from-sage via-dark-forest to-transparent"></div>
              </div>
              <h3 className="text-xl font-semibold text-dark-forest dark:text-pale-lime mb-3">Calculate</h3>
              <p className="text-gray-700 dark:text-gray-300">
                Use our easy carbon calculator to measure your carbon footprint based on your lifestyle, travel habits, home energy use, and food choices.
              </p>
            </motion.div>

            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              variants={fadeIn}
              className="text-center"
            >
              <div className="relative mx-auto mb-6 w-20 h-20 flex items-center justify-center bg-sage/20 rounded-full shadow-inner">
                <span className="text-dark-forest font-bold text-3xl">2</span>
                <div className="absolute -right-10 top-5 hidden md:block w-24 h-1 bg-gradient-to-r from-sage via-dark-forest to-transparent"></div>
              </div>
              <h3 className="text-xl font-semibold text-dark-forest dark:text-pale-lime mb-3">Reduce</h3>
              <p className="text-gray-700 dark:text-gray-300">
                Get personalized recommendations to reduce your footprint through simple lifestyle changes and track your progress over time.
              </p>
            </motion.div>

            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              variants={fadeIn}
              className="text-center"
            >
              <div className="relative mx-auto mb-6 w-20 h-20 flex items-center justify-center bg-sage/20 rounded-full shadow-inner">
                <span className="text-dark-forest font-bold text-3xl">3</span>
              </div>
              <h3 className="text-xl font-semibold text-dark-forest dark:text-pale-lime mb-3">Offset</h3>
              <p className="text-gray-700 dark:text-gray-300">
                Support verified carbon offset projects that align with your values to neutralize the emissions you can't eliminate.
              </p>
            </motion.div>
          </div>
          
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="mt-12 relative h-96 w-full rounded-xl overflow-hidden shadow-xl"
          >
            <Image 
              src="/images/carbon-offset-process.jpg" 
              alt="Carbon offset process" 
              fill
              style={{ objectFit: 'cover' }}
              className="hover-zoom"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-dark-forest/60 to-transparent flex items-end p-8">
              <div className="text-white max-w-2xl">
                <h3 className="text-2xl font-bold mb-3">Your Impact Matters</h3>
                <p className="text-lg">
                  Individual actions add up to make a significant difference. By understanding, reducing, and offsetting your carbon footprint, you're contributing to global climate solutions.
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Solutions Grid */}
      <section id="solutions" className="section bg-pale-lime/20 dark:bg-gray-900/50">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="text-center mb-16"
          >
            <h2 className="text-3xl font-bold text-dark-forest dark:text-pale-lime mb-5">Our Solutions for Individuals</h2>
            <p className="max-w-3xl mx-auto text-gray-700 dark:text-gray-300">
              Comprehensive tools and services to help you take meaningful climate action in your everyday life.
            </p>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
            variants={staggerContainer}
            className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 grid-gap-lg"
          >
            {solutions.map((solution, index) => (
              <motion.div 
                key={index}
                variants={fadeIn}
                className="card card-hover"
              >
                <div className="card-body">
                  <div className="flex items-start mb-4">
                    <div className="bg-sage/20 p-4 rounded-lg mr-4">
                      <div className="text-dark-forest text-2xl">
                        {solution.icon}
                      </div>
                    </div>
                    <h3 className="text-xl font-semibold text-dark-forest dark:text-pale-lime mt-2">{solution.title}</h3>
                  </div>
                  <p className="text-gray-700 dark:text-gray-300">{solution.description}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Impact Numbers */}
      <section className="section">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="text-center mb-16"
          >
            <h2 className="text-3xl font-bold text-dark-forest dark:text-pale-lime mb-5">Our Collective Impact</h2>
            <p className="max-w-3xl mx-auto text-gray-700 dark:text-gray-300">
              Together, our community of climate-conscious individuals is making a significant positive impact on the planet.
            </p>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
            variants={staggerContainer}
            className="grid grid-cols-2 md:grid-cols-4 grid-gap-lg"
          >
            {impactNumbers.map((item, index) => (
              <motion.div 
                key={index}
                variants={fadeIn}
                className="text-center"
              >
                <div className="bg-sage/20 p-6 rounded-xl shadow-soft">
                  <p className="text-3xl md:text-4xl font-bold text-dark-forest dark:text-pale-lime mb-2">
                    {item.value}
                  </p>
                  <p className="text-gray-700 dark:text-gray-300">
                    {item.label}
                  </p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="section bg-pale-lime/20 dark:bg-gray-900/50">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="text-center mb-16"
          >
            <h2 className="text-3xl font-bold text-dark-forest dark:text-pale-lime mb-5">What Our Users Say</h2>
            <p className="max-w-3xl mx-auto text-gray-700 dark:text-gray-300">
              Real stories from people who have transformed their relationship with the environment through our platform.
            </p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 grid-gap-lg">
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              variants={fadeIn}
              className="card card-hover"
            >
              <div className="card-body">
                <div className="flex justify-center mb-4">
                  <div className="text-dark-forest">
                    {[...Array(5)].map((_, i) => (
                      <span key={i} className="text-sage text-xl">★</span>
                    ))}
                  </div>
                </div>
                <p className="text-gray-700 dark:text-gray-300 mb-5 italic">
                  "The carbon calculator opened my eyes to how my daily choices impact the environment. I've reduced my footprint by 30% in just 6 months with the personalized tips."
                </p>
                <div className="flex items-center">
                  <div className="relative w-12 h-12 rounded-full overflow-hidden mr-4">
                    <Image 
                      src="/images/testimonials/user1.jpg" 
                      alt="Sarah K." 
                      fill
                      style={{ objectFit: 'cover' }}
                    />
                  </div>
                  <div>
                    <h3 className="font-medium text-dark-forest dark:text-pale-lime">Sarah K.</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-400">New York, NY</p>
                  </div>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              variants={fadeIn}
              className="card card-hover"
            >
              <div className="card-body">
                <div className="flex justify-center mb-4">
                  <div className="text-dark-forest">
                    {[...Array(5)].map((_, i) => (
                      <span key={i} className="text-sage text-xl">★</span>
                    ))}
                  </div>
                </div>
                <p className="text-gray-700 dark:text-gray-300 mb-5 italic">
                  "I love being able to directly support specific projects that align with my values. Knowing exactly where my money goes and the impact it has is incredibly rewarding."
                </p>
                <div className="flex items-center">
                  <div className="relative w-12 h-12 rounded-full overflow-hidden mr-4">
                    <Image 
                      src="/images/testimonials/user2.jpg" 
                      alt="Marcus T." 
                      fill
                      style={{ objectFit: 'cover' }}
                    />
                  </div>
                  <div>
                    <h3 className="font-medium text-dark-forest dark:text-pale-lime">Marcus T.</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Portland, OR</p>
                  </div>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={{ once: true, amount: 0.3 }}
              variants={fadeIn}
              className="card card-hover"
            >
              <div className="card-body">
                <div className="flex justify-center mb-4">
                  <div className="text-dark-forest">
                    {[...Array(5)].map((_, i) => (
                      <span key={i} className="text-sage text-xl">★</span>
                    ))}
                  </div>
                </div>
                <p className="text-gray-700 dark:text-gray-300 mb-5 italic">
                  "The monthly subscription makes it easy to maintain carbon neutrality with minimal effort. I set it up once and can live my life knowing I'm offsetting what I can't reduce."
                </p>
                <div className="flex items-center">
                  <div className="relative w-12 h-12 rounded-full overflow-hidden mr-4">
                    <Image 
                      src="/images/testimonials/user3.jpg" 
                      alt="Elena R." 
                      fill
                      style={{ objectFit: 'cover' }}
                    />
                  </div>
                  <div>
                    <h3 className="font-medium text-dark-forest dark:text-pale-lime">Elena R.</h3>
                    <p className="text-sm text-gray-600 dark:text-gray-400">Austin, TX</p>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="section">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="text-center mb-16"
          >
            <h2 className="text-3xl font-bold text-dark-forest dark:text-pale-lime mb-5">Common Questions</h2>
            <p className="max-w-3xl mx-auto text-gray-700 dark:text-gray-300">
              Everything you need to know about personal carbon offsetting and how our platform works.
            </p>
          </motion.div>

          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.1 }}
            variants={staggerContainer}
            className="max-w-4xl mx-auto space-y-6"
          >
            {faqs.map((faq, index) => (
              <motion.div 
                key={index}
                variants={fadeIn}
                className="card card-hover"
              >
                <div className="card-body">
                  <h3 className="text-xl font-semibold text-dark-forest dark:text-pale-lime mb-3">{faq.question}</h3>
                  <p className="text-gray-700 dark:text-gray-300">{faq.answer}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Get Started CTA */}
      <section className="section bg-pale-lime/20 dark:bg-gray-900/50">
        <div className="container">
          <motion.div
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, amount: 0.3 }}
            variants={fadeIn}
            className="max-w-4xl mx-auto bg-dark-forest text-white rounded-2xl p-8 md:p-12 shadow-xl relative overflow-hidden"
          >
            {/* Decorative elements */}
            <div className="absolute inset-0 overflow-hidden z-0">
              <div className="absolute -right-10 -top-10 w-64 h-64 rounded-full bg-sage/20 blur-2xl"></div>
              <div className="absolute -left-10 bottom-0 w-48 h-48 rounded-full bg-pale-lime/10 blur-2xl"></div>
            </div>
            
            <div className="relative z-10 text-center">
              <h2 className="text-3xl md:text-4xl font-bold mb-6">Ready to Take Climate Action?</h2>
              <p className="text-lg md:text-xl mb-8 text-gray-200">
                Join thousands of individuals who are making a positive impact on the planet through carbon reduction and offsetting.
              </p>
              <div className="flex flex-col sm:flex-row gap-5 justify-center">
                <Link href="/calculator" className="btn bg-sage hover:bg-pale-lime hover:text-dark-forest text-dark-forest font-medium transition-all duration-300">
                  Calculate Your Footprint
                </Link>
                <Link href="/contact" className="btn border border-white text-white hover:bg-white hover:text-dark-forest transition-all duration-300">
                  Contact Us
                </Link>
              </div>
            </div>
          </motion.div>
        </div>
      </section>
    </main>
  );
} 